[package]
name = "builder"
version = "0.1.0"
edition.workspace = true
publish = false
default-run = "builder"

[[bin]]
name = "builder"
path = "main.rs"

[dependencies]
retgui_builder = { path = "../../builder" }
util = { path = "../util" }

[dependencies.retgui]
path = "../../retgui"
default-features = false
features = ["system_fonts", "clipboard", "vello_hybrid_renderer"]
